// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9b5329839558a78550bf078c3e5f323c2f0f3b86/redux-devtools/index.d.ts
declare module 'redux-devtools' {
// Type definitions for redux-devtools 3.0.0
// Project: https://github.com/gaearon/redux-devtools
// Definitions by: Petryshyn Sergii <https://github.com/mc-petry>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.1

import * as React from 'react';
import { GenericStoreEnhancer } from 'redux';

export interface IDevTools {
    new (): JSX.ElementClass;
    instrument(): GenericStoreEnhancer
}

export function createDevTools(el: React.ReactElement<any>): IDevTools;
export function persistState(debugSessionKey: string): GenericStoreEnhancer;

const factory: { instrument(): (opts: any) => any };

export default factory;
}
